### ISSUE TITLE
Apagar este repositório

### ISSUE THREAD

**Issue by felipelalli** [btcbrdev/btcbrdev.github.io#1]
Este repositório está vazio, qual é a sua utilidade?

**Comment by paladini** [comment]
Também não sei a finalidade desse repo, mas acredito que seja criar uma página para o grupo. É para isso, @Anderson-Juhasc ?

**Comment by felipelalli** [comment]
Se for isso então vou fechar, achei que tivesse sido um teste. :)

**Comment by rands0n** [comment]
É para criar uma página para o grupo mesmo. Esse repositório é o repo "mãe" da organização.

Ele pode ser acessado por http://btcbrdev.github.io

**Comment by felipelalli** [comment]
Aqui não abriu essa URL.

**Comment by paladini** [comment]
É que o repositório está vazio, não existe um site (ainda).

**Comment by rands0n** [comment]
Da uma olhada agora :tada:

**Comment by paladini** [comment]
Grande @randsonjs !!! :)

**Comment by Anderson-Juhasc** [comment]
É a página para o grupo como o @randsonjs disse.

**Comment by felipelalli** [comment]
Legal!
