### ISSUE TITLE
Criar a conta no Twitter

### ISSUE THREAD

**Issue by levinobre** [btcbrdev/btcbrdev.github.io#3]
Olá pessoal, tô aqui só pra perguntar, o que acham deu criar uma conta no Twitter pra organização? Eu publicaria sobre os andamentos dos repositórios, etc, seria coisa boba, só pra ter a marca da organização mesmo, o que acham?

**Comment by randsonjs** [comment]
Acho ótimo, uma conta do facebook também!

**Comment by Anderson-Juhasc** [comment]
Se vocês acham que é necessário para agora, por mim tudo bem.

**Comment by levinobre** [comment]
Certo, uma conta ou página? Me passem os usuários de vocês no Twitter :)

**Comment by paladini** [comment]
@nandopaladini

**Comment by randsonjs** [comment]
@randsonjs

**Comment by Anderson-Juhasc** [comment]
@Anderson_Juhasc

**Comment by Anderson-Juhasc** [comment]
Página do FB

**Comment by felipelalli** [comment]
@micaroni3
